name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=development" >> $GITHUB_OUTPUT
          fi

      - name: Build binaries
        run: |
          GOOS=darwin GOARCH=amd64 go build -o lazycommit-darwin-amd64 -ldflags="-X main.version=${{ steps.get_version.outputs.VERSION }}" ./cmd/lazycommit
          GOOS=darwin GOARCH=arm64 go build -o lazycommit-darwin-arm64 -ldflags="-X main.version=${{ steps.get_version.outputs.VERSION }}" ./cmd/lazycommit
          GOOS=linux GOARCH=amd64 go build -o lazycommit-linux-amd64 -ldflags="-X main.version=${{ steps.get_version.outputs.VERSION }}" ./cmd/lazycommit
          GOOS=linux GOARCH=arm64 go build -o lazycommit-linux-arm64 -ldflags="-X main.version=${{ steps.get_version.outputs.VERSION }}" ./cmd/lazycommit

          # Create zip archives
          mkdir -p dist
          zip -j dist/lazycommit-darwin-amd64.zip lazycommit-darwin-amd64
          zip -j dist/lazycommit-darwin-arm64.zip lazycommit-darwin-arm64
          zip -j dist/lazycommit-linux-amd64.zip lazycommit-linux-amd64
          zip -j dist/lazycommit-linux-arm64.zip lazycommit-linux-arm64

          # Create checksums
          cd dist
          sha256sum *.zip > checksums.txt

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/lazycommit-darwin-amd64.zip
            dist/lazycommit-darwin-arm64.zip
            dist/lazycommit-linux-amd64.zip
            dist/lazycommit-linux-arm64.zip
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: lazycommit-binaries
          path: dist/
          retention-days: 7
